# サイト全体で使うメタデータ
---

url: http://unformedbuilding.com
title: Unformed Building
description: Web制作に関係する勉強の記録と覚え書き
separator: " | "
author:
    name:
        en: Matori
        ja: まとり
    mail: pnr.matori@gmail.com
    twitter:
        id: 25670065
        name: ub_pnr
